---
name: Release latest

on:
  push:
    branches:
      - main

jobs:
  # Push to latest
  container-push-latest:
    uses: metal-toolbox/container-push/.github/workflows/container-push.yml@main
    with:
      name: porton
      tag: latest
      registry_org: ${{ github.repository }}
      dockerfile_path: Dockerfile
      platforms: linux/amd64,linux/arm64